# Setup
title: Enormousness
url: http://enormousness.net
paginate: 1
baseurl: ""
permalink: pretty
include: ["_pages"]

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Kelsey Neis
  url: http://enormousness.net
  email: kneis@protonmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Recipes
    url: /archive

  - title: About
    url: /about
    
collections:
  tags:
    output: true
    permalink: tag/:title/

defaults:
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag
